services:
  # node web service
  - type: web
    name: Wework-Chatgpt
    env: node
    rootDir: .
    autoDeploy: false
    repo: https://github.com/sytpb/chatgpt-wework-robot # optional
    region: singapore     # optional (defaults to oregon)
    plan: free            # optional (defaults to starter instance type)
    branch: main          # optional (defaults to master)
    healthCheckPath: /healthz
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        sync: false
      - key: AGENTID
        sync: false
      - key: TOKEN
        sync: false
      - key: CORPID
        sync: false
      - key: AESKEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET
        sync: false